"""empty message

Revision ID: 3e6b3be70b10
Revises: 7127a63e8129
Create Date: 2020-08-26 18:07:51.082153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e6b3be70b10'
down_revision = '7127a63e8129'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###
