"""empty message

Revision ID: 7127a63e8129
Revises: ed6469bac000
Create Date: 2020-08-26 17:09:19.979972

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7127a63e8129'
down_revision = 'ed6469bac000'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_image', mysql.VARCHAR(length=256), nullable=True))
    # ### end Alembic commands ###
